show databases;
create database stud;
use stud;
show tables;
create table student(id int,name varchar(100),age int,dob date);
insert into student values(1,'ajith',26,'2025-01-01'),(2,'vikram',25,'2024-01-01');
desc student;
insert into student(id,age) values (3,27),(4,26);
select * from student;
set sql_safe_updates = 0;
update student set age = 28 where id = 2;
update student set dob = '2024-01-01' where dob is null;
set autocommit = 0;
update student set name = 'yash' where id = 3;
update student set name = 'ram' where id = 4;
delete from student;
rollback;
select * from student;
alter table student add column email varchar(100);
alter table student add column student_code varchar(5) first;
alter table student add column surname varchar(2) after id;
update student set student_code = 'S001' ,surname = 's', email = 'a@gmail.com' where id = 1;
update student set student_code = 'S002' ,surname = 'r', email = 'v@gmail.com' where id = 2;
update student set student_code = 'S003' ,surname = 'b', email = 'y@gmail.com' where id = 3;
update student set student_code = 'S004' ,surname = 'a', email = 'r@gmail.com' where id = 4;
select * from student;
