show databases;
use ds;
show tables;
create table stud(id int,name varchar(100),age int,dob date);
insert into stud values(1,'Ajith',28,'2023-01-01'),(2,'Murari',29,'2021-01-01');
select * from stud;
insert into stud (id,dob) values (3,'2021-01-01'),(4,'2020-01-01');
set sql_safe_updates = 0;
update stud set age = 28 where age is null;
update stud set name = 'Hari' where name is null;
update stud set name = 'Yash',age = 24 where id = 3;
insert into stud (id,dob) values (5,'2021-01-01'),(6,'2020-01-01');
update stud set name = 'Viki',age = 29 where name is null and age is null;
update stud set name = 'Yum',age = 26 where id = 6;
set autocommit = 0;
insert into stud (id) values (7),(8);
delete from stud where name is null;
rollback;
delete from stud;
alter table stud add column percentage float;
select * from stud;
alter table stud add column stud_code varchar(6) first;
alter table stud add column email varchar(60) after dob;
alter table stud rename column stud_code to code;
desc stud;
alter table stud modify column id char(2);
alter table stud modify column name int;
alter table stud modify column id int;
alter table stud drop column email;
rename table stud to students;
create database data;
show databases;
use data;
show tables;
create table stud(id int,name varchar(30));
insert into stud values(1,'na'),(2,'hm');
select * from stud;
alter table stud drop column name;
drop table stud;
truncate table stud;
rollback;
drop database data;
